# Generated by Django 4.1.3 on 2022-11-11 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_refund_refund_amount_remove_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='cancelled_order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='time_of_refund',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='username',
            field=models.CharField(default='hardik', max_length=255),
            preserve_default=False,
        ),
    ]
