# Generated by Django 4.1.3 on 2022-11-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0001_initial'),
        ('payments', '0005_refund_cancelled_order_id_refund_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=20)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.serviceorder')),
            ],
        ),
    ]
