# Generated by Django 4.1.3 on 2022-11-11 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_color_name_alter_warranty_warranty_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_upto',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 6, 59, 42, 650749)),
        ),
    ]
