# Generated by Django 4.1.3 on 2022-11-11 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_warranty_warranty_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_upto',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 10, 49, 48, 278373)),
        ),
    ]
