# Generated by Django 4.1.3 on 2022-11-11 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_alter_warranty_warranty_upto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.DateField(default=datetime.datetime(2022, 11, 13, 18, 21, 58, 107876))),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=255)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bike')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='technician', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
