# Generated by Django 4.1.3 on 2022-11-11 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 18, 35, 39, 151548)),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
