# Generated by Django 4.1.3 on 2022-11-11 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_alter_serviceorder_estimated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 18, 53, 47, 829758)),
        ),
    ]
