# Generated by Django 4.1.3 on 2022-11-12 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0005_alter_serviceorder_estimated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='estimated_time',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='estimated_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 14, 10, 51, 24, 41878), null=True),
        ),
    ]
