# Generated by Django 4.1.3 on 2022-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cancelledorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledorder',
            name='refund',
        ),
        migrations.AddField(
            model_name='cancelledorder',
            name='refund_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelledorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
